### ISSUE TITLE
Compiled binaries

### ISSUE THREAD

**Issue by notatestuser** [CityOfZion/neo-gui-developer#19]
Hi!
Could we have compiled binaries released on GitHub here for those of us not into using Windows platforms?

**Comment by canesin** [comment]
@notatestuser neo-gui-developer is windows only.

**Comment by notatestuser** [comment]
Yeah so what I mean is I have a Windows VM but would like to run neo-gui-developer on it without unboxing all the Visual Studio and .NET frameworks on it.
