### ISSUE TITLE
Passing parameters when invoking contract

### ISSUE THREAD

**Issue by Andromelus** [CityOfZion/neo-gui-developer#32]
Hi.

I watched the video, but really, passing parameters when involing the contract is not clear at all.

So here is what I am trying to do:

http://prntscr.com/hgmflg

I want to pass a simple string to the contract. But when passing "Test" as parameter, it changes to ByteArray automaticaly. And I got the error displayed in the screenshot, what ever the tye of parameter I put.

Can someone explain **clearly** how to pass parameters?

**Comment by ghost** [comment]
At the time this was written strings were being passed as byte arrays. closing this as it isn't really an issue - feel free to jump on discord for help with usage
