### ISSUE TITLE
source code compile error

### ISSUE THREAD

**Issue by vicraft18** [CityOfZion/neo-gui-developer#33]
![compile_error](https://user-images.githubusercontent.com/34088375/33363504-942c31c0-d51b-11e7-9859-3fd99320350a.png)
i'm getting a compile time error 
'CX509PrivateKey' does not contain a definition for 'AlgorithmName' and no extension method 'AlgorithmName' accepting a first argument of type 'CX509PrivateKey' could be found
if anyone suggest a fix that will be great, if not can someone send me a x64 version .exe file?

**Comment by tommyleo** [comment]
Same problem here!

**Comment by dheeraj-palagiri-biggroup** [comment]
Same issue

**Comment by jonatanblockchain** [comment]
Operating System? Win7 or Win10?

**Comment by dheeraj-palagiri-biggroup** [comment]
Windows 7

Dheeraj Palagiri
Developer

BIG GROUP
CELEBRATING 25 YEARS

Switch: +44 (0) 20 7229 8827

91 Princedale Rd, Holland Park, London W11 4NS
Registered in England: 2520892

www.biggroup.co.uk<http://www.biggroup.co.uk/>
www.twitter.com/biggrouplondon<http://www.twitter.com/biggrouplondon/>

**Comment by jonatanblockchain** [comment]
AlgorithmName is available on Windows 10.
https://github.com/neo-project/neo-gui/issues/97

**Comment by iNomaD** [comment]
The same issue. So is it possible to build the program on Win7 x64?

Could you please provide compiled binaries?

**Comment by ghost** [comment]
We have no plans to start releasing compiled binaries for this repository..

In regards to the original bug: https://github.com/neo-project/neo-gui/issues/97
