### ISSUE TITLE
Build Error: MainForm.resx - Invalid ResX-File.

### ISSUE THREAD

**Issue by nrrso** [CityOfZion/neo-gui-developer#34]
While trying to build the gui, I got the following error:

`Ungültige ResX-Datei. Der angeforderte Wert "Ctrl" konnte nicht gefunden werden. `
`Zeile 573, Position 5.`

Translated: `Invalid ResX-File. The required value "Ctrl" could not be found.`

As it turns out, I had to translate 

> Ctrl

 to 

> Strg 

(for Germany), which fixed the error. This fix may be different if the locale of your System or Visual Studio is different.

**Comment by ghost** [comment]
should probably be reported on neo-project/neo-gui if this is still an issue
