### ISSUE TITLE
Faulting module name: KERNELBASE.dll

### ISSUE THREAD

**Issue by dheeraj-palagiri-biggroup** [CityOfZion/neo-gui-developer#36]
App Crashes on Windows 10 and event log has below errors:

> .NET Runtime version 4.0.30319.0 - Loading profiler failed during CoCreateInstance.  Profiler CLSID: '{68130646-C19E-459E-8BF4-5137ED7B3FD7}'.  HRESULT: 0x8007007e.  Process ID (decimal): 5648.  Message ID: [0x2504].

> Application: neo-gui.exe
> Framework Version: v4.0.30319
> Description: The process was terminated due to an unhandled exception.
> Exception Info: System.IO.FileNotFoundException
>    at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean)
>    at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(System.Collections.Generic.IList`1<Microsoft.Extensions.Configuration.IConfigurationProvider>)
>    at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
>    at Neo.Properties.Settings..ctor()
>    at Neo.Properties.Settings..cctor()
> 
> Exception Info: System.TypeInitializationException
>    at Neo.Properties.Settings.get_Default()
>    at Neo.Program.InstallCertificate()
>    at Neo.Program.Main()

> Faulting application name: neo-gui.exe, version: 2.3.6600.23928, time stamp: 0x5a6b2a70
> Faulting module name: KERNELBASE.dll, version: 10.0.16299.15, time stamp: 0x4736733c
> Exception code: 0xe0434352

**Comment by ghost** [comment]
https://github.com/neo-project/neo-gui/issues/5
