### ISSUE TITLE
neo-gui-developer crashes when syncing to testnet

### ISSUE THREAD

**Issue by swdevMPaul** [CityOfZion/neo-gui-developer#37]
Hi,

I have compiled(built) the neo-gui-developer in release and debug modes. While neo-gui synced on testnet, the neo-gui-developer (both release and debug versions) crashes on some block while syncing on testnet. 

I think the source codes have to be reviewed.

There were problems in neo-gui-developer also in:

Program->InstallCertificate():

System.TypeInitializationException: 'The type initializer for 'Neo.Properties.Settings' threw an exception.'

Why ?

How to get it synced to the testnet?

Kind Regards.

**Comment by ghost** [comment]
more information is required: please provide a stack trace and the block number if it consistently crashes on a certain block..
