### ISSUE TITLE
Need to merge with neo-project/neo-gui's latest commit

### ISSUE THREAD

**Issue by farukterzioglu** [CityOfZion/neo-gui-developer#42]
There are huge changes in this commit;
https://github.com/neo-project/neo-gui/commit/adefd4b88da52a430df8afe6aa495b974ebdfaa2
Merging this will be hard.

**Comment by ghost** [comment]
i have a copy of neo-gui-developer already up to date with neo-project/neo-gui which i was planning to commit but you beat me to it. i've reverted most of the invoke contract dialog changes that i've made and was working on getting the runtime notifications working again.

**Comment by farukterzioglu** [comment]
I would do it, and actually started, but it will take some time and I don't have enough time to merge that last commit :(

**Comment by ghost** [comment]
all good, its done: https://github.com/CityOfZion/neo-gui-developer/pull/43
