### ISSUE TITLE
Doesn't display update button in a set parameters window.

### ISSUE THREAD

**Issue by divyang-desai** [CityOfZion/neo-gui-developer#49]
Not able to set parameters while invoking the contract, there is no update button.

<img width="424" alt="neo-gui-developer issue" src="https://user-images.githubusercontent.com/13957507/38072704-3051f1ac-3345-11e8-931f-023ec7144b85.PNG">

**Comment by ghost** [comment]
Won't be addressing this as parameter editor in dev build is the tree editor. If you wish to use this please checkout https://github.com/birmas/neo-gui-developer/tree/dev-updates for short term

**Comment by Cody1988** [comment]
I encounter the problem too
